from datetime import date

MIN_ISBN_LENGTH = 10
MAX_ISBN_LENGTH = 13

MIN_TITLE_LENGTH = 1
MAX_TITLE_LENGTH = 255

MIN_AUTHOR_LENGTH = 1
MAX_AUTHOR_LENGTH = 255

MIN_PAGES = 1
MAX_PAGES = 20000

MIN_LANGUAGE_LENGTH = 2
MAX_LANGUAGE_LENGTH = 8

CURRENT_YEAR = date.today().year
MIN_YEAR = 1450

MAX_BOOK_DESCRIPTION_LENGTH = 2000
