MIN_USERNAME_LENGTH = 3
MAX_USERNAME_LENGTH = 32

MIN_EMAIL_LENGTH = 3
MAX_EMAIL_LENGTH = 254
MAX_LOCAL_PART = 64

MIN_FIRST_NAME_LENGTH = 1
MAX_FIRST_NAME_LENGTH = 100

MIN_LAST_NAME_LENGTH = 1
MAX_LAST_NAME_LENGTH = 100


