from typing import Protocol
from app.domain.user.user_entity import User


class UserRepository(Protocol):
    async def save(self, user: User) -> User: ...
    async def exists_by_email(self, email: str) -> bool: ...
    async def exists_by_username(self, username: str) -> bool: ...
    async def find_user_by_email(self, email: str) -> User | None: ...
    async def find_user_by_username(self, username: str) -> User | None: ...
