from typing import Protocol
from uuid import UUID
from app.domain.book.book_entity import BookEntity, NewBookEntity


class AdminBookRepository(Protocol):
    async def create(self, newbook: NewBookEntity) -> None: ...
    async def exists_by_isbn(self, isbn: str) -> bool: ...
    async def find_all(self) -> list[BookEntity]: ...
    async def find_by_id(self, id: UUID) -> BookEntity | None: ...
